// Задание 1
let password = 'пароль';
let paswordRequest = prompt('Введите пароль');
if (password === paswordRequest) {
    alert('Пароль введен верно');
} else {
    alert('Пароль введен неправильно');
}
// Задание 2
let c = prompt ('Введите число');
if (c>0 && c<10) {console.log ('Верно')
 } else {console.log ('Не верно')
 }
 // Задание 3
 let d = prompt('Введите число');
 let c = prompt('Введите число');
 if (d>100 || c>100) {console.log ('Верно')
 } else {console.log ('Не верно')
 }